package per.zpp.settings.mapper;

import per.zpp.settings.domain.DicValue;

import java.util.List;

public interface DicValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Thu Aug 10 19:28:10 CST 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Thu Aug 10 19:28:10 CST 2023
     */
    int insert(DicValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Thu Aug 10 19:28:10 CST 2023
     */
    int insertSelective(DicValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Thu Aug 10 19:28:10 CST 2023
     */
    DicValue selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Thu Aug 10 19:28:10 CST 2023
     */
    int updateByPrimaryKeySelective(DicValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Thu Aug 10 19:28:10 CST 2023
     */
    int updateByPrimaryKey(DicValue record);


    /**
     * 通过自定义的类型编码查询对应的字典表数据
     * @param typeCode 类型编码
     * @return 对应字典表数据
     */
    List<DicValue> selectDicValueByTypeCode(String typeCode);

    /**
     * 通过id查询对应的字典表数据
     * @param id 字典数据id
     * @return 字典表数据
     */
    DicValue selectDicValueById(String id);
}